version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flowise.rule=Host(`e.odx.kz`)"  # Ваш домен
      - "traefik.http.routers.flowise.entrypoints=websecure"  # HTTPS
      - "traefik.http.routers.flowise.tls.certresolver=myresolver"  # Let's Encrypt
      - "traefik.http.services.flowise.loadbalancer.server.port=3000"
    networks:
      - app-net
      - traefik_traefik-net

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_pass
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
  traefik_traefik-net:
    external: true
